---
kind: pipeline
name: default

steps:
    - name: scan-build
      image: debian:stretch
      pull: true
      commands:     
      - apt-get update && apt-get install -yq git build-essential autotools-dev lsb-release pkg-config automake autoconf libtool-bin clang-tools-4.0
      - apt-get install -yq cmake uuid-dev libssl1.0-dev      
      - git clone https://github.com/signalwire/libks libks
      - cd libks && cmake . -DCMAKE_BUILD_TYPE=Release && make && make install && cd ..
      - sed -i '/cotire/d' ./CMakeLists.txt
      - sed -i '/cotire/d' ./swclt_test/CMakeLists.txt
      - mkdir -p scan-build
      - scan-build-4.0 -o ./scan-build/ cmake .
      - echo '#!/bin/bash\nscan-build-4.0 -o ./scan-build/ make -j`nproc --all` |& tee ./scan-build-result.txt\nexitstatus=$${PIPESTATUS[0]}\necho $$exitstatus > ./scan-build-status.txt\n' > scan.sh
      - chmod +x scan.sh
      - ./scan.sh
      - exitstatus=`cat ./scan-build-status.txt`
      - echo "*** Exit status is $exitstatus"

    - name: notify
      image: signalwire/drone-notify
      pull: true
      environment:
        SLACK_WEBHOOK_URL:
          from_secret: slack_webhook_url
        ENV_FILE:
          from_secret: notify_env
      commands:
      - /root/scan-build-notify.sh
      
trigger:
  branch:
  - master  

trigger:
  event:
  - pull_request
  - push
---
kind: signature
hmac: 088f9c09ab42cfd913a9575b9f5e835d909e7ac59cc612f93957ef7fa330c6f4

...
